#!/usr/bin/env node
/**
 * export-wiki.mjs — publish a wiki node as a standalone HTML file (#459).
 *
 *   node export-wiki.mjs 12 --out ~/Desktop/architecture.html
 *   node export-wiki.mjs 12 --dry-run       # transform + check, emit nothing
 *
 * Why this exists as a build step rather than a careful manual pass: the room's
 * wiki keeps the room's real language, and adaptation for an outside reader
 * happens at this boundary. A manual pass can quietly widen its own scope — a
 * declared rule list in EXPORT_TRANSFORMS.json cannot, and the fail-closed
 * check below means "the scrub happened" is a property of the mechanism instead
 * of a claim by whoever ran it.
 *
 * Reads the LIVE node over the REST API (never board-data.json directly).
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import { transformForExport } from './core/export-transforms.mjs';
import { renderExportHtml } from './core/export-html.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const API = process.env.SCRUM_API || `http://127.0.0.1:${process.env.SCRUM_PORT || 3141}`;

const die = (msg) => { console.error(`\n✗ ${msg}\n`); process.exit(1); };

function parseArgs(argv) {
  const args = { id: null, out: null, dryRun: false, config: join(HERE, 'EXPORT_TRANSFORMS.json') };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--dry-run') args.dryRun = true;
    else if (a === '--out') args.out = argv[++i];
    else if (a === '--config') args.config = argv[++i];
    else if (!a.startsWith('-') && args.id === null) args.id = a;
    else die(`unrecognised argument: ${a}`);
  }
  if (!args.id) die('usage: node export-wiki.mjs <node-id> [--out FILE] [--dry-run]');
  if (!args.out && !args.dryRun) args.out = resolve(`wiki-${args.id}-export.html`);
  return args;
}

async function fetchNode(id) {
  let res;
  try {
    res = await fetch(`${API}/api/nodes/${id}`);
  } catch {
    die(`cannot reach the board API at ${API} — is server.js running?`);
  }
  if (!res.ok) die(`GET /api/nodes/${id} → HTTP ${res.status}`);
  const payload = await res.json();
  // GET returns {node, children, backlinks}; the content lives on node.text.
  const node = payload.node || payload;
  if (!node || typeof node.text !== 'string') die(`node ${id} has no text content`);
  return node;
}

const main = async () => {
  const args = parseArgs(process.argv.slice(2));

  let config;
  try {
    config = JSON.parse(readFileSync(args.config, 'utf8'));
  } catch (err) {
    die(`could not read transform config ${args.config} — ${err.message}`);
  }

  const node = await fetchNode(args.id);
  const title = node.name || `Node ${args.id}`;

  // Fail-closed: throws, loudly, if any forbidden term survived the rules.
  let scrubbed;
  try {
    scrubbed = transformForExport(node.text, config);
  } catch (err) {
    die(err.message);
  }

  const applied = (config.rules || []).filter((r) => {
    try { return new RegExp(r.find, r.flags || 'g').test(node.text); } catch { return false; }
  });

  const exportedAt = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
  const digest = createHash('sha256').update(scrubbed).digest('hex').slice(0, 12);

  const html = renderExportHtml(scrubbed, {
    title,
    sourceLabel: `wiki #${node.identifier ?? args.id}`,
    exportedAt,
    digest,
    sourceModified: node.dateModified,
    note: 'Generated by export-wiki.mjs. Some in-house names are substituted at export; the source retains them.',
  });

  console.log(`\n  ${title}`);
  console.log(`  source        wiki #${node.identifier ?? args.id} (modified ${node.dateModified || 'unknown'})`);
  console.log(`  markdown      ${node.text.length.toLocaleString()} chars → html ${html.length.toLocaleString()} chars`);
  console.log(`  transforms    ${applied.length}/${(config.rules || []).length} rules matched:`);
  for (const r of applied) console.log(`                  ${r.find.slice(0, 58)}${r.find.length > 58 ? '…' : ''}`);
  console.log(`  scrub check   PASS — 0 of ${(config.forbidden || []).length} forbidden patterns present`);
  console.log(`  digest        ${digest}`);

  if (args.dryRun) { console.log('\n  --dry-run: nothing written.\n'); return; }

  writeFileSync(args.out, html, 'utf8');
  console.log(`  written       ${args.out}\n`);
};

main().catch((err) => die(err.stack || String(err)));
